services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=billing'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - ./sql:/sql:ro